export {default as HomeScreen} from './HomeScreen/HomeScreen'
export {default as Dashboard} from './Dashboard/Dashboard'
export {default as Profile} from './Profile/Profile'
export {default as UserDashboard} from './UserDashboard/UserDashboard'
export {default as AddRecord} from './AddRecord/AddRecord'
